# Generated by Django 4.1.7 on 2023-05-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subject_college_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='college_adminID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
    ]
