# Generated by Django 4.1.7 on 2023-05-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subject_college_adminid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='college_adminID',
            new_name='subject_adminID',
        ),
    ]
